package:
  name: abaqus_tools
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://github.com/lanl/tardigrade-abaqus-tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of tools for C++ that make interfacing with Abaqus subroutines easier and less prone to error.'
  description: |
    tardigrade-abaqus-tools (C20048 Tardigrade) A collection of tools for C++ that make interfacing with Abaqus
    subroutines easier and less prone to error.
  doc_url: https://lanl.github.io/tardigrade-abaqus-tools
  dev_url: https://github.com/lanl/tardigrade-abaqus-tools

source:
  path: '..'

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --install . --prefix $PREFIX
  ignore_run_exports:
    - python_abi

requirements:
  host:
    - {{ compiler('cxx') }}
    - python
    - setuptools_scm >=6.2
    - cmake >=3.18
    - eigen >=3.3.7
    - vector_tools >=0.6 # TODO: Separate the package/test configuration to make vector_tools and optional build dependency
    - boost >=1.59  # TODO: Separate the package/test configuration to make BOOST an optional build dependency
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  run:
    - eigen >=3.3.7

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - boost >=1.59
    - vector_tools >=0.6
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_abaqus_tools.cpp
  commands:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build . --target test_abaqus_tools
    - ctest -R test_abaqus_tools
