package:
  name: abaqus_tools
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --install . --prefix $PREFIX
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - eigen >=3.3.7
    - boost >=1.59  # TODO: Separate the package/test configuration to make BOOST an optional build dependency
    - vector_tools  # TODO: Separate the package/test configuration to make vector_tools and optional build dependency
    - setuptools_scm >=6.2
  host:
    - python
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  run:
    - {{ compiler('cxx') }}
    - eigen >=3.3.7

test:
  requires:
    - cmake >=3.18
    - boost >=1.59
    - vector_tools
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_abaqus_tools.cpp
  commands:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test
    - cmake --build . --target test_abaqus_tools
    - ctest -R test_abaqus_tools
